<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ajitas-MBP.attlocal.net" ignored="0" name="RetryMultipleTestCases" tests="9" failures="2" timestamp="06 Oct 2020 00:20:58 GMT" time="0.041" errors="0">
  <testcase name="Test1" time="0.008" classname="MyTests.MyTests2">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="MyTests.MyTests2">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="MyTests.MyTests2">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="MyTests.MyTests2">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at MyTests.MyTests2.Test1(MyTests2.java:9)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.001" classname="MyTests.MyTests2">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="MyTests.MyTests2">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="MyTests.MyTests2">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="MyTests.MyTests2">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at MyTests.MyTests2.Test2(MyTests2.java:14)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.001" classname="MyTests.MyTests2"/>
</testsuite> <!-- RetryMultipleTestCases -->
